'use client';
import {useState} from 'react';
import {BookOpen, Brain, ChevronRight, ClipboardCheck, GraduationCap, Home, LayoutDashboard, Menu, Plus, Search, Settings, Sparkles, Target, Users, X, BarChart3} from 'lucide-react';

const nav=[['Overview',LayoutDashboard],['Curriculum',BookOpen],['AI Generator',Sparkles],['Assessments',ClipboardCheck],['Students',Users],['Analytics',BarChart3]] as const;
const subjects=[{name:'Mathematics',topics:42,color:'var(--lav)'},{name:'Physics',topics:36,color:'var(--mint)'},{name:'Computer Science',topics:31,color:'var(--pink)'},{name:'English',topics:28,color:'var(--yellow)'}];
const recent=[['Algebra — Linear Equations','Mathematics','12 MCQs','2 min ago'],['Newton’s Laws','Physics','8 MCQs','18 min ago'],['Data Structures','Computer Science','10 MCQs','1 hr ago']];

export default function HomePage(){
 const [active,setActive]=useState('Overview'); const [open,setOpen]=useState(false);
 return <div className="min-h-screen flex">
  <aside className={`${open?'fixed inset-0 z-50':'hidden'} lg:flex lg:static w-full lg:w-64 bg-white border-r border-slate-100 p-5 flex-col`}>
   <div className="flex items-center justify-between mb-10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-[var(--lav)] flex items-center justify-center"><GraduationCap size={22}/></div><div><div className="font-bold">Punjab Edu</div><div className="text-xs text-slate-400">Intelligence Platform</div></div></div><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div>
   <div className="text-[11px] uppercase tracking-wider text-slate-400 px-3 mb-2">Workspace</div>
   <nav className="space-y-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>{setActive(label);setOpen(false)}} className={`w-full flex items-center gap-3 px-3 py-3 rounded-2xl text-sm transition ${active===label?'bg-[var(--lav)] font-semibold':'text-slate-500 hover:bg-slate-50'}`}><Icon size={18}/>{label}<ChevronRight className="ml-auto" size={15}/></button>)}</nav>
   <div className="mt-auto rounded-3xl p-4 bg-[var(--yellow)]"><div className="font-semibold text-sm">AI content ready</div><p className="text-xs text-slate-600 mt-1">Generate curriculum-aligned questions in seconds.</p><button onClick={()=>setActive('AI Generator')} className="mt-3 bg-white rounded-xl px-3 py-2 text-xs font-semibold">Let's create</button></div>
   <button className="mt-3 flex items-center gap-3 px-3 py-3 text-sm text-slate-500"><Settings size={18}/>Settings</button>
  </aside>
  <main className="flex-1 min-w-0">
   <header className="h-20 bg-white/90 backdrop-blur border-b border-slate-100 flex items-center justify-between px-5 lg:px-9 sticky top-0 z-20"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div><div className="text-xs text-slate-400">Friday, October 2, 2026</div><h1 className="text-xl lg:text-2xl font-semibold">Hi, Danielle <span>👋</span></h1></div></div><div className="flex items-center gap-3"><div className="hidden md:flex items-center gap-2 bg-slate-50 rounded-2xl px-3 py-2 text-sm text-slate-400"><Search size={16}/><span>Search curriculum...</span></div><div className="w-10 h-10 rounded-full bg-[var(--pink)] flex items-center justify-center font-semibold">D</div></div></header>
   <section className="p-5 lg:p-9 max-w-7xl mx-auto">
    <div className="grid xl:grid-cols-[1.35fr_.65fr] gap-5">
     <div className="rounded-[30px] p-7 lg:p-9 bg-[var(--lav)] soft-shadow relative overflow-hidden"><div className="max-w-xl"><div className="inline-flex items-center gap-2 bg-white/70 rounded-full px-3 py-1 text-xs font-semibold"><Sparkles size={14}/> AI learning assistant</div><h2 className="text-3xl lg:text-4xl font-bold mt-5 leading-tight">Build better learning journeys from the Punjab curriculum.</h2><p className="mt-3 text-slate-600 max-w-lg">Choose a topic, generate assessments, and turn student attempts into actionable insights.</p><button onClick={()=>setActive('AI Generator')} className="mt-6 bg-[var(--pink)] px-5 py-3 rounded-2xl font-semibold flex items-center gap-2">Start generating <ChevronRight size={17}/></button></div><div className="absolute -right-8 -bottom-16 w-48 h-48 rounded-full bg-white/35"/></div>
     <div className="rounded-[30px] p-7 bg-white soft-shadow"><div className="flex justify-between"><div><div className="text-sm text-slate-400">Today</div><div className="text-3xl font-bold mt-1">82%</div><div className="text-sm text-slate-500 mt-1">Average student mastery</div></div><div className="w-12 h-12 rounded-2xl bg-[var(--mint)] flex items-center justify-center"><Target/></div></div><div className="mt-7 h-3 bg-slate-100 rounded-full overflow-hidden"><div className="h-full w-[82%] bg-[var(--mint)] rounded-full"/></div><div className="mt-5 grid grid-cols-2 gap-3"><Stat label="Active students" value="1,248"/><Stat label="Assessments" value="326"/></div></div>
    </div>
    <div className="flex items-center justify-between mt-9 mb-4"><div><h3 className="text-xl font-bold">Curriculum overview</h3><p className="text-sm text-slate-400 mt-1">Explore your active subjects and topics.</p></div><button onClick={()=>setActive('Curriculum')} className="text-sm font-semibold flex items-center gap-1">View all <ChevronRight size={16}/></button></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{subjects.map((s,i)=><div key={s.name} className="bg-white rounded-[25px] p-5 soft-shadow"><div className="w-11 h-11 rounded-2xl flex items-center justify-center" style={{background:s.color}}><BookOpen size={20}/></div><h4 className="font-semibold mt-4">{s.name}</h4><p className="text-sm text-slate-400 mt-1">{s.topics} topics</p><div className="mt-4 flex items-center justify-between text-xs"><span className="text-slate-400">Mastery</span><b>{[84,76,88,72][i]}%</b></div><div className="mt-2 h-2 bg-slate-100 rounded-full"><div className="h-full rounded-full" style={{width:`${[84,76,88,72][i]}%`,background:s.color}}/></div></div>)}</div>
    <div className="grid xl:grid-cols-[1fr_.8fr] gap-5 mt-9"><div className="bg-white rounded-[28px] p-6 soft-shadow"><div className="flex justify-between items-center"><div><h3 className="font-bold text-lg">Recent AI-generated content</h3><p className="text-sm text-slate-400">Latest assessment material</p></div><button className="w-10 h-10 rounded-xl bg-[var(--yellow)] flex items-center justify-center"><Plus size={18}/></button></div><div className="mt-5 divide-y divide-slate-100">{recent.map(r=><div key={r[0]} className="py-4 flex items-center gap-4"><div className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center"><Brain size={18}/></div><div className="min-w-0 flex-1"><div className="font-medium text-sm truncate">{r[0]}</div><div className="text-xs text-slate-400 mt-1">{r[1]} · {r[2]}</div></div><span className="text-xs text-slate-400">{r[3]}</span></div>)}</div></div>
    <div className="bg-white rounded-[28px] p-6 soft-shadow"><h3 className="font-bold text-lg">Quick actions</h3><div className="grid grid-cols-2 gap-3 mt-5"><Action title="Generate MCQs" color="var(--lav)" onClick={()=>setActive('AI Generator')}/><Action title="Create quiz" color="var(--pink)" onClick={()=>setActive('Assessments')}/><Action title="View students" color="var(--mint)" onClick={()=>setActive('Students')}/><Action title="Open analytics" color="var(--yellow)" onClick={()=>setActive('Analytics')}/></div></div></div>
   </section>
  </main>
 </div>
}
function Stat({label,value}:{label:string,value:string}){return <div className="bg-slate-50 rounded-2xl p-3"><div className="text-xs text-slate-400">{label}</div><div className="font-bold mt-1">{value}</div></div>}
function Action({title,color,onClick}:{title:string,color:string,onClick:()=>void}){return <button onClick={onClick} className="text-left p-4 rounded-2xl hover:-translate-y-0.5 transition" style={{background:color}}><div className="font-semibold text-sm">{title}</div><ChevronRight size={16} className="mt-3"/></button>}
